// cmd/export.go
package cmd

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/julienpequegnot/ghmon/internal/account"
	"github.com/julienpequegnot/ghmon/internal/activity"
	"github.com/julienpequegnot/ghmon/internal/analysis"
	"github.com/julienpequegnot/ghmon/internal/config"
	"github.com/julienpequegnot/ghmon/internal/database"
	"github.com/spf13/cobra"
)

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "Generate markdown report",
	Long:  `Exports activity digest as markdown for sharing or archiving.`,
	RunE:  runExport,
}

var (
	exportDays int
)

func init() {
	rootCmd.AddCommand(exportCmd)
	exportCmd.Flags().IntVar(&exportDays, "days", 7, "Number of days to include in export")
}

func runExport(cmd *cobra.Command, args []string) error {
	db, err := database.New(config.DBPath())
	if err != nil {
		return fmt.Errorf("failed to open database: %w", err)
	}
	defer db.Close()

	since := time.Now().AddDate(0, 0, -exportDays)
	endDate := time.Now()

	accountRepo := account.NewRepository(db)
	commitRepo := activity.NewCommitRepository(db)
	repoRepo := activity.NewRepoRepository(db)
	starRepo := activity.NewStarRepository(db)

	accounts, _ := accountRepo.List()
	accountMap := make(map[int64]*account.Account)
	for i := range accounts {
		accountMap[accounts[i].ID] = &accounts[i]
	}

	commitCounts, _ := commitRepo.CountByAccount(since)
	newRepos, _ := repoRepo.GetNewSince(since)
	recentStars, _ := starRepo.GetSince(since)
	trendingRepos, _ := starRepo.GetTrendingRepos(since, 2)

	totalCommits := 0
	for _, c := range commitCounts {
		totalCommits += c
	}

	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# GitHub Activity Digest\n\n"))
	sb.WriteString(fmt.Sprintf("**Period:** %s - %s\n\n",
		since.Format("January 2, 2006"),
		endDate.Format("January 2, 2006")))

	// Summary
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Accounts monitored:** %d\n", len(accounts)))
	sb.WriteString(fmt.Sprintf("- **Total commits:** %d\n", totalCommits))
	sb.WriteString(fmt.Sprintf("- **New repositories:** %d\n", len(newRepos)))
	sb.WriteString(fmt.Sprintf("- **Stars given:** %d\n\n", len(recentStars)))

	// Most Active
	if len(commitCounts) > 0 {
		sb.WriteString("## Most Active\n\n")
		sb.WriteString("| Developer | Commits |\n")
		sb.WriteString("|-----------|--------:|\n")

		type accountCommits struct {
			username string
			count    int
		}
		var sorted []accountCommits
		for accID, count := range commitCounts {
			if acc, ok := accountMap[accID]; ok {
				sorted = append(sorted, accountCommits{acc.Username, count})
			}
		}
		sort.Slice(sorted, func(i, j int) bool {
			return sorted[i].count > sorted[j].count
		})

		limit := 10
		if len(sorted) < limit {
			limit = len(sorted)
		}
		for i := 0; i < limit; i++ {
			sb.WriteString(fmt.Sprintf("| [%s](https://github.com/%s) | %d |\n",
				sorted[i].username, sorted[i].username, sorted[i].count))
		}
		sb.WriteString("\n")
	}

	// New Repositories
	if len(newRepos) > 0 {
		sb.WriteString("## New Repositories\n\n")

		limit := 10
		if len(newRepos) < limit {
			limit = len(newRepos)
		}
		for i := 0; i < limit; i++ {
			repo := newRepos[i]
			desc := repo.Description
			if desc == "" {
				desc = "*No description*"
			}
			sb.WriteString(fmt.Sprintf("- [%s](https://github.com/%s) - %s\n",
				repo.FullName, repo.FullName, desc))
		}
		sb.WriteString("\n")
	}

	// Trending Repos
	if len(trendingRepos) > 0 {
		sb.WriteString("## Trending (Starred by Multiple Follows)\n\n")

		for _, t := range trendingRepos {
			sb.WriteString(fmt.Sprintf("- [%s](https://github.com/%s) - ★ by %s\n",
				t.RepoFullName, t.RepoFullName, strings.Join(t.StarredBy, ", ")))
		}
		sb.WriteString("\n")
	}

	// Languages
	langStats := analysis.AnalyzeLanguages(newRepos, recentStars)
	if len(langStats) > 0 {
		sb.WriteString("## Languages\n\n")
		sb.WriteString("| Language | Activity |\n")
		sb.WriteString("|----------|--------:|\n")

		for _, lang := range langStats {
			sb.WriteString(fmt.Sprintf("| %s | %.0f%% |\n", lang.Language, lang.Percentage))
		}
		sb.WriteString("\n")
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("*Generated by [ghmon](https://github.com/julienpequegnot/ghmon) on %s*\n",
		time.Now().Format("2006-01-02 15:04")))

	fmt.Print(sb.String())
	return nil
}
